### PR TITLE
Repair the main Player system to behave like current BloomReader

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/16)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/16)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/layout.less, line 112 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/16#-LU7FtKdDVOH_O5uzFp_:-LU7FtKdDVOH_O5uzFpa:b5mp5j8) ([raw file](https://github.com/bloombooks/bloomplayer/blob/1883d27357263811f4312656db89eeee6740474e/src/layout.less#L112)):*
> ```Less
> // the 100% rule.
> // The conditions of this rule duplicate the mess that the features.less creates for the width: 100% rule.
> body[data-bffullscreenpicture*="allMedia"][data-bffullscreenpicture*="allOrientations"] .bloom-imageContainer,
> ```

Yep, that's ugly. : )

Is there any reasonable way to simplify this using a mixin?
___
*[src/layout.ts, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/16#-LU7Fj4q3dStNfyirPOe:-LU7Fj4q3dStNfyirPOf:b-6s6nw4) ([raw file](https://github.com/bloombooks/bloomplayer/blob/1883d27357263811f4312656db89eeee6740474e/src/layout.ts#L31)):*
> ```
> document.body.getAttribute("data-bffullscreenpicture")
> ```
Probably not worth it, but could check that the value of data-bffullscreenpicture contains `landscape` or `allOrientations`?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/16)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/layout.less, line 112 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/16#-LU7FtKdDVOH_O5uzFp_:-LU7Qg7e7P8xaD__xLuP:b5odsx) ([raw file](https://github.com/bloombooks/bloomplayer/blob/1883d27357263811f4312656db89eeee6740474e/src/layout.less#L112)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yep, that's ugly. : )

Is there any reasonable way to simplify this using a mixin?
</blockquote></details>

Done. (Using the mixins from features.less)
___
*[src/layout.ts, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/16#-LU7Fj4q3dStNfyirPOe:-LU7R6ckBtgVfz5b3lT6:b-896fix) ([raw file](https://github.com/bloombooks/bloomplayer/blob/1883d27357263811f4312656db89eeee6740474e/src/layout.ts#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> document.body.getAttribute("data-bffullscreenpicture")
> ```
Probably not worth it, but could check that the value of data-bffullscreenpicture contains `landscape` or `allOrientations`?
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/16)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/layout.less, line 111 at r2](https://reviewable.io/reviews/bloombooks/bloomplayer/16#-LU7RID35ThpfI7q91mJ:-LU7RID46u-UuDNo0IZe:b-i03173) ([raw file](https://github.com/bloombooks/bloomplayer/blob/804e0383af43821e2cf96614cd2bf5fff07f2a65/src/layout.less#L111)):*
> ```
> features.less
> ```
Bloom's bookFeatures.less

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/16)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/layout.less, line 111 at r2](https://reviewable.io/reviews/bloombooks/bloomplayer/16#-LU7RID35ThpfI7q91mJ:-LU7Se3I6EV-QRE4ZrsJ:b-ydonir) ([raw file](https://github.com/bloombooks/bloomplayer/blob/804e0383af43821e2cf96614cd2bf5fff07f2a65/src/layout.less#L111)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> features.less
> ```
Bloom's bookFeatures.less
</blockquote></details>

Done. Good idea.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/16)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
