### PR TITLE
Send more media status to Bloom Reader (or whomever) (BL-7003)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/21)

### CODE REVIEW

**Review by rjconrad — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/21)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/pagePlayer/app.ts, line 120 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/21#-LbgQtfi8ktL_1oH9lO3:-LbgQtfi8ktL_1oH9lO4:bh7m0is) ([raw file](https://github.com/bloombooks/bloomplayer/blob/d9e5033436bf4ccef96379cc14c52aae34529388/src/pagePlayer/app.ts#L120)):*
> ```XML
>     /* tslint:disable:no-string-literal */
>     if (page) {
>         status["hasNarration"] = Narration.pageHasNarration(page);
> ```

Out of curiosity why `status["hasNarration"]` instead of `status.hasNarration`? Then you probably wouldn't have to disable that linter check. You could even write it
```
const status = page ? {
  hasNarration: Narration.pageHasNarration(page),
  hasAnimation: Animation.pageHasAnimation(page),
  ...
} : {
  hasNarration: false,
  hasAnimation: false,
  ...
}
```

Or did I miss something?

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/21)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @rjconrad)

___
*[src/pagePlayer/app.ts, line 120 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/21#-LbgQtfi8ktL_1oH9lO3:-LbhyjrX48_HajnnKVJI:bjdk7qt) ([raw file](https://github.com/bloombooks/bloomplayer/blob/d9e5033436bf4ccef96379cc14c52aae34529388/src/pagePlayer/app.ts#L120)):*
<details><summary><i>Previously, rjconrad (Rick Conrad) wrote…</i></summary><blockquote>

Out of curiosity why `status["hasNarration"]` instead of `status.hasNarration`? Then you probably wouldn't have to disable that linter check. You could even write it
```
const status = page ? {
  hasNarration: Narration.pageHasNarration(page),
  hasAnimation: Animation.pageHasAnimation(page),
  ...
} : {
  hasNarration: false,
  hasAnimation: false,
  ...
}
```

Or did I miss something?
</blockquote></details>

The compiler complained about undefined properties when I tried it the other way.  I guess I can bite the bullet and define a class structure for the return value.  It would be more principled to do it that way.  :-)

**Comment by rjconrad** [comment]
I'm pretty sure if you use that second syntax I described, there won't be a
problem with undefined properties since you create the whole object at once.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/21)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @rjconrad)

___
*[src/pagePlayer/app.ts, line 120 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/21#-LbgQtfi8ktL_1oH9lO3:-Lbi7Op353g2fAa6YVNX:b-896fix) ([raw file](https://github.com/bloombooks/bloomplayer/blob/d9e5033436bf4ccef96379cc14c52aae34529388/src/pagePlayer/app.ts#L120)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The compiler complained about undefined properties when I tried it the other way.  I guess I can bite the bullet and define a class structure for the return value.  It would be more principled to do it that way.  :-)
</blockquote></details>

Done.

**Review by rjconrad — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/21)* status: all files reviewed, 1 unresolved discussion (waiting on @rjconrad)

**Pull request merged**
