### PR TITLE
Handle new Talking Book format (4.6) to handle soft-split mode (BL-7537)

### PR DESCRIPTION
**Pull request by jsubloom**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23)

### CODE REVIEW

**Review by jsubloom — COMMENTED** [review]
FYI, I added a ton of static modifiers because the class is designed slightly differently, and removed all the strict null checking to make it compatible with Typescript 1.8.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23#-:-LmFpiy27pGQv_Co7Ppe:b-4l3i9k)* status: 0 of 1 files reviewed, 1 unresolved discussion

___
*[src/pagePlayer/narration.ts, line 516 at r1](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23#-LmFpcXj48IqPQatHdXO:-LmFpcXj48IqPQatHdXP:b5e1s9) ([raw file](https://github.com/bloombooks/legacybloomplayer/blob/6a6a366421e043ec7b7d09139078c940f0042be7/src/pagePlayer/narration.ts#L516)):*
> ```
> if (!currentTimeInSecs || currentTimeInSecs <= 0) {
>             currentTimeInSecs = startTimeInSecs;
> ```

Brand new code.
___
*[src/pagePlayer/narration.ts, line 576 at r1](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23#-LmFpEOzA7TvqyHP0vX3:-LmFpEOzA7TvqyHP0vX4:bf1xkt8) ([raw file](https://github.com/bloombooks/legacybloomplayer/blob/6a6a366421e043ec7b7d09139078c940f0042be7/src/pagePlayer/narration.ts#L576)):*
> ```XML
>     // Removes the .ui-audioCurrent class from all elements
>     // Equivalent of removeAudioCurrentFromPageDocBody() in BloomDesktop.
>     private static removeAudioCurrent() {
> ```

FYI, this function's implementation is written slightly differently than in the new bloom-player. Due to differences in typescript versions, the other code used a classes (HTMLCollectionOf) and a method (Array.from) which weren't available.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23)* status: all files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/pagePlayer/narration.ts, line 577 at r2](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23#-LmG2juhDv9Eo40ybLy2:-LmG2juhDv9Eo40ybLy3:bm2ultd) ([raw file](https://github.com/bloombooks/legacybloomplayer/blob/d1827937cab06c15b021e968b345d3d92e25d87c/src/pagePlayer/narration.ts#L577)):*
> ```XML
>     // Equivalent of removeAudioCurrentFromPageDocBody() in BloomDesktop.
>     private static removeAudioCurrent() {
>         // Note that HTMLCollectionOf's length can change if you change the number of elements matching the selector.
> ```

I think this comment needs updating/removing?
___
*[src/pagePlayer/narration.ts, line 580 at r2](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23#-LmG3jTY0KQilbRHDm3f:-LmG3jTY0KQilbRHDm3g:b-pr0rvw) ([raw file](https://github.com/bloombooks/legacybloomplayer/blob/d1827937cab06c15b021e968b345d3d92e25d87c/src/pagePlayer/narration.ts#L580)):*
> ```XML
>         const audioCurrentCollection = document.getElementsByClassName("ui-audioCurrent");
> 
>         // Convert to an array whose length won't be changed
> ```

It seems that if audioCurrentCollection.length is volatile, this won't work. 
If it isn't, I don't think we need the extra array.

**Review by jsubloom — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/pagePlayer/narration.ts, line 577 at r2](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23#-LmG2juhDv9Eo40ybLy2:-LmGAaDV69skb1ofGGUe:b-896fix) ([raw file](https://github.com/bloombooks/legacybloomplayer/blob/d1827937cab06c15b021e968b345d3d92e25d87c/src/pagePlayer/narration.ts#L577)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this comment needs updating/removing?
</blockquote></details>

Done.
___
*[src/pagePlayer/narration.ts, line 580 at r2](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23#-LmG3jTY0KQilbRHDm3f:-LmGAaYgDuPPIl-tDtLs:b-634a78) ([raw file](https://github.com/bloombooks/legacybloomplayer/blob/d1827937cab06c15b021e968b345d3d92e25d87c/src/pagePlayer/narration.ts#L580)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It seems that if audioCurrentCollection.length is volatile, this won't work. 
If it isn't, I don't think we need the extra array.
</blockquote></details>

Oh... that's a good catch. I lucked out because the length is usually 1, but that could end badly otherwise.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23)* status: all files reviewed, 1 unresolved discussion

**Review by andrew-polk — APPROVED** [review]
> Dismissed @sujeffreyl from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/legacybloomplayer/23)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
