### PR TITLE
Fix audio playback on Android 4.4 (BL-6888)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/18)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
It comments on the obvious and doesn't explain the obscurities it uses at all, but we  clearly need the polyfill, so if this is the official recommended one, I suppose it's best we use it.

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/18#-:-LYXjz_bAD2-9Ny0WTIs:bc1msjr)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/pagePlayer/app.ts, line 168 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/18#-LYXjYVx-61vRkfoooR2:-LYXjYVx-61vRkfoooR3:b-d3wdkj) ([raw file](https://github.com/bloombooks/bloomplayer/blob/291666c161a594e2b19f4ea94c7fdec3a57a5af5/src/pagePlayer/app.ts#L168)):*
> ```XML
> 
>       // 4. If thisArg was supplied, let T be thisArg; else let T be undefined.
>       var thisArg = arguments[1];
> ```

I suppose they know what they're doing; but I thought 'this' was normally arguments[0]?
___
*[src/pagePlayer/app.ts, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/18#-LYXiB8F3-W2Cwk_Qs1R:-LYXiB8F3-W2Cwk_Qs1S:b2oelm8) ([raw file](https://github.com/bloombooks/bloomplayer/blob/291666c161a594e2b19f4ea94c7fdec3a57a5af5/src/pagePlayer/app.ts#L175)):*
> ```XML
>       // 6. Repeat, while k < len
>       while (k < len) {
>         // a. Let Pk be ! ToString(k).
> ```

The comments in this polyfill are some of the worst I've ever seen for stating the obvious rather than anything useful. But this one is instead actually wrong: there's no Pk variable and nothing I can see calls ToString() (nor should, for any reason I can see).

**Review by andrew-polk — COMMENTED** [review]
Good point. I originally used a much simpler version but then thought maybe I should use the one from MDN.
The reason the comments are so hokey, apparently, is the copied the algorithm as comments from https://tc39.github.io/ecma262/#sec-array.prototype.find.
I think I'll go back to the original implementation I had found.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/18#-:-LYXmvht5lbo47WenPdc:b-ex9o3s)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/18)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/pagePlayer/app.ts, line 168 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/18#-LYXjYVx-61vRkfoooR2:-LYXrIrl6wKbnKMiICZD:b6ofu4s) ([raw file](https://github.com/bloombooks/bloomplayer/blob/291666c161a594e2b19f4ea94c7fdec3a57a5af5/src/pagePlayer/app.ts#L168)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose they know what they're doing; but I thought 'this' was normally arguments[0]?
</blockquote></details>

It appears that predicate is arguments[0]??
So maybe this is arguments[0] if the function doesn't take any parameters?
___
*[src/pagePlayer/app.ts, line 175 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/18#-LYXiB8F3-W2Cwk_Qs1R:-LYXpptT7UEdzMbErwVi:b-896fix) ([raw file](https://github.com/bloombooks/bloomplayer/blob/291666c161a594e2b19f4ea94c7fdec3a57a5af5/src/pagePlayer/app.ts#L175)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The comments in this polyfill are some of the worst I've ever seen for stating the obvious rather than anything useful. But this one is instead actually wrong: there's no Pk variable and nothing I can see calls ToString() (nor should, for any reason I can see).
</blockquote></details>

Done.

**Review by JohnThomson — APPROVED** [review]
Looks better to me.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/18#-:-LYXwFXn9YVapNrl7csg:b-rspus0)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
