### PR TITLE
BL-6695 and 6693 give player video pause/play

### PR DESCRIPTION
**Pull request by gmartin7**
* 1st commit is refactoring
* setup pagePlayer so an app (like BR) can call in
   and start or pause video playback.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/14)

### CODE REVIEW

**Comment by gmartin7** [comment]
This PR is a prerequisite for changes to Bloom Reader that handle starting and pausing video playback.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/14)* status: all files reviewed, 4 unresolved discussions (waiting on @gmartin7)

___
*[src/pagePlayer/app.ts, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSv29-13NVVhW4sErvQ:-LSv29-13NVVhW4sErvR:b-kam12) ([raw file](https://github.com/bloombooks/bloomplayer/blob/6607f232415c338c6b29490e782f1157121a48c3/src/pagePlayer/app.ts#L77)):*
> ```XML
> 
> // Tells app (Android or other) whether the current page has multimedia or not.
> export function requestPageMultimediaState(): string {
> ```

Assume this can't return boolean because of the interaction with the app side?
___
*[src/pagePlayer/app.ts, line 83 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSv4Kt41GJQ3W8xTMcF:-LSv4Kt41GJQ3W8xTMcG:bwlce1v) ([raw file](https://github.com/bloombooks/bloomplayer/blob/6607f232415c338c6b29490e782f1157121a48c3/src/pagePlayer/app.ts#L83)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         if (initialized) {
>             return getPageMultimediaState();
>         } else {
>             initialize();
>             return getPageMultimediaState();
>         }
> ```
</details>

 This would be cleaner as 
```
if (!initialized)
  initialize()
return getPageMultimediaState();
```
___
*[src/pagePlayer/app.ts, line 90 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSv2EUj8mYpb2nOoKMm:-LSv2EUj8mYpb2nOoKMn:bawx5wj) ([raw file](https://github.com/bloombooks/bloomplayer/blob/6607f232415c338c6b29490e782f1157121a48c3/src/pagePlayer/app.ts#L90)):*
> ```XML
> }
> 
> function getPageMultimediaState(): string {
> ```

It seems cleaner to make this return boolean and call it PageHasMultimedia or, since it seems that these functions are already in the context of a specific page, just HasMultimedia.
___
*[src/pagePlayer/app.ts, line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSv3dVTA9Q_fmeThVuI:-LSv3dVTA9Q_fmeThVuJ:b-vq4was) ([raw file](https://github.com/bloombooks/bloomplayer/blob/6607f232415c338c6b29490e782f1157121a48c3/src/pagePlayer/app.ts#L91)):*
> ```XML
> 
> function getPageMultimediaState(): string {
>     const page = <HTMLElement> (document.body.querySelector(".bloom-page"));
> ```

Can we set page as a member variable when the initialization happens so we don't have to keep finding it?

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/14)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[src/pagePlayer/app.ts, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSv29-13NVVhW4sErvQ:-LSv5RsG-Hgstc83tg5_:b-48305o) ([raw file](https://github.com/bloombooks/bloomplayer/blob/6607f232415c338c6b29490e782f1157121a48c3/src/pagePlayer/app.ts#L77)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Assume this can't return boolean because of the interaction with the app side?
</blockquote></details>

Yes, I'll make a comment.
___
*[src/pagePlayer/app.ts, line 83 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSv4Kt41GJQ3W8xTMcF:-LSv5ZDnCiWU1UnyLe-y:b-ovwaw7) ([raw file](https://github.com/bloombooks/bloomplayer/blob/6607f232415c338c6b29490e782f1157121a48c3/src/pagePlayer/app.ts#L83)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>         if (initialized) {
>             return getPageMultimediaState();
>         } else {
>             initialize();
>             return getPageMultimediaState();
>         }
> ```
 This would be cleaner as 
```
if (!initialized)
  initialize()
return getPageMultimediaState();
```
</blockquote></details>

Good idea.
___
*[src/pagePlayer/app.ts, line 90 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSv2EUj8mYpb2nOoKMm:-LSv7D6hBIRlbpK2rQVP:b-8cuxp5) ([raw file](https://github.com/bloombooks/bloomplayer/blob/6607f232415c338c6b29490e782f1157121a48c3/src/pagePlayer/app.ts#L90)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It seems cleaner to make this return boolean and call it PageHasMultimedia or, since it seems that these functions are already in the context of a specific page, just HasMultimedia.
</blockquote></details>

Done. Of course I still had to turn it into a string in the caller.
___
*[src/pagePlayer/app.ts, line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSv3dVTA9Q_fmeThVuI:-LSvGmqMCnJUDM_p9Gu1:b77up1l) ([raw file](https://github.com/bloombooks/bloomplayer/blob/6607f232415c338c6b29490e782f1157121a48c3/src/pagePlayer/app.ts#L91)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Can we set page as a member variable when the initialization happens so we don't have to keep finding it?
</blockquote></details>

Done. That simplifies a number of places. It's actually a global variable, since this .ts file has no class and therefore no member variables.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/14)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/14)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/pagePlayer/narration.ts, line 53 at r3](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSvN31d2TRSgH0lWORh:-LSvN31d2TRSgH0lWORi:b-1v1kno) ([raw file](https://github.com/bloombooks/bloomplayer/blob/2cc2a553d56c4bdfbd954ab6f0c9edcb300ec003/src/pagePlayer/narration.ts#L53)):*
> ```XML
>     }
> 
>     public static pageHasNarration(page: HTMLDivElement): boolean {
> ```

@gmartin7 what if the book has narration in English, but Spanish is being displayed?

**Comment by gmartin7** [comment]
___
*[src/pagePlayer/narration.ts, line 53 at r3](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSvN31d2TRSgH0lWORh:-LSvOYii6tb4DlcWzBMr:b-e77he7) ([raw file](https://github.com/bloombooks/bloomplayer/blob/2cc2a553d56c4bdfbd954ab6f0c9edcb300ec003/src/pagePlayer/narration.ts#L53)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

@gmartin7 what if the book has narration in English, but Spanish is being displayed?
</blockquote></details>

Sorry, didn't think of that. I was just using the logic of `documentHasNarration()` to see if the page has narration.

**Comment by andrew-polk** [comment]
___
*[src/pagePlayer/narration.ts, line 53 at r3](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSvN31d2TRSgH0lWORh:-LSvSM9V4APZv4sij_g0:b7uv751) ([raw file](https://github.com/bloombooks/bloomplayer/blob/2cc2a553d56c4bdfbd954ab6f0c9edcb300ec003/src/pagePlayer/narration.ts#L53)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Sorry, didn't think of that. I was just using the logic of `documentHasNarration()` to see if the page has narration.
</blockquote></details>

Good point. Looks like a gap in our logic for both. This has been merged. @gmartin7, would you mind creating a card?

**Comment by gmartin7** [comment]
___
*[src/pagePlayer/narration.ts, line 53 at r3](https://reviewable.io/reviews/bloombooks/bloomplayer/14#-LSvN31d2TRSgH0lWORh:-LSzBYdjE9eX7lcg9P9d:b-896fix) ([raw file](https://github.com/bloombooks/bloomplayer/blob/2cc2a553d56c4bdfbd954ab6f0c9edcb300ec003/src/pagePlayer/narration.ts#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Good point. Looks like a gap in our logic for both. This has been merged. @gmartin7, would you mind creating a card?
</blockquote></details>

Done.

**Pull request merged**
