### PR TITLE
BL-5109 support android animation

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/3)

### CODE REVIEW

**Comment by hatton** [comment]
Can't say I follow it all, but :lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomplayer/3#-:-KxsSRQxqYGr_DWsmbXf:b-imypoa)*

**Comment by JohnThomson** [comment]
Let's not merge this yet. I have one more problem to solve.

**Comment by andrew-polk** [comment]
:lgtm: 
I added a couple niggles; probably not worth another commit.

@john_thomson, your last comment says don't merge. But that is not true anymore, correct?

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/pagePlayer/animation.ts, line 57 at r2](https://reviewable.io:443/reviews/bloombooks/bloomplayer/3#-Kxwe7zBzwPZZuIwCzif:-Kxwe7zBzwPZZuIwCzig:bt0ve93) ([raw file](https://github.com/bloombooks/bloomplayer/blob/00be42b52dc50db8df3ecfd0435610ed24fc3207/src/pagePlayer/animation.ts#L57)):*
> setShouldAnimateInAllOrientations

This seems like an odd paradigm. Why not pass in the value you want to set it to?

---

*[src/pagePlayer/app.ts, line 35 at r2](https://reviewable.io:443/reviews/bloombooks/bloomplayer/3#-KxwfPMY5xc94THufNy2:-KxwfPMY5xc94THufNy3:bsojzh5) ([raw file](https://github.com/bloombooks/bloomplayer/blob/00be42b52dc50db8df3ecfd0435610ed24fc3207/src/pagePlayer/app.ts#L35)):*
> otherwise, we were called before doc loaded, when it is we will proceed.

otherwise, we were called before doc loaded; when it is we will proceed.
or
otherwise, we were called before doc loaded. When it is we will proceed.

Same below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomplayer/3#-:-KxwgEeQ2gu58WX82Vs6:bdsg12m)*

**Comment by JohnThomson** [comment]
Should all be good now; ready to merge.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/pagePlayer/animation.ts, line 57 at r2](https://reviewable.io:443/reviews/bloombooks/bloomplayer/3#-Kxwe7zBzwPZZuIwCzif:-Kxx1HhxxlQrh0-tVS5i:b-g7gssy) ([raw file](https://github.com/bloombooks/bloomplayer/blob/00be42b52dc50db8df3ecfd0435610ed24fc3207/src/pagePlayer/animation.ts#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> setShouldAnimateInAllOrientations

This seems like an odd paradigm. Why not pass in the value you want to set it to?
</blockquote></details>

Done. (Though YAGNI?)

---

*[src/pagePlayer/app.ts, line 35 at r2](https://reviewable.io:443/reviews/bloombooks/bloomplayer/3#-KxwfPMY5xc94THufNy2:-Kxx1KsABweCHlY7C2-M:b-896fix) ([raw file](https://github.com/bloombooks/bloomplayer/blob/00be42b52dc50db8df3ecfd0435610ed24fc3207/src/pagePlayer/app.ts#L35)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> otherwise, we were called before doc loaded, when it is we will proceed.

otherwise, we were called before doc loaded; when it is we will proceed.
or
otherwise, we were called before doc loaded. When it is we will proceed.

Same below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomplayer/3#-:-Kxx1EiTBZfsxX2sXLIT:b22r2mo)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/bloomplayer/3)*

**Pull request merged**
