### PR TITLE
BL-7255 Add callback to get length of video played

### PR DESCRIPTION
**Pull request by JohnThomson**
Plus some automatic formatting changes

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/22)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Seems like this is just giving us the length of all the video elements if they were to be played. But the analytics question is how much video was actually played.
Or am I missing something?

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/22#-:-Li9L5iJ8dGimKd5WBlD:bfsm6js)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/pagePlayer/app.ts, line 122 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/22#-Li9KS3zCdqMmV3OCd-f:-Li9KS4-6rdZQtsNGety:b-lrx0a6) ([raw file](https://github.com/bloombooks/bloomplayer/blob/1461e42c4bb5552dadf0920476eec781c4210147/src/pagePlayer/app.ts#L122)):*
> ```
> totalVideoLength
> ```
getTotalVideoLength?

**Review by JohnThomson — COMMENTED** [review]
Well, BloomPlayer as used in BR1.x is only looking at a page at a time. The reader knows (and controls) which pages are actually played. So this is good enough unless we want to take account of pausing and playing within the page. But I guess you're saying we should?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/22#-:-Li9bbk-8Holx08L1DTj:b-yxxe31)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
Switched to  a completely different approach.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/22#-:-LiAI5I98TlIP_VCBx7d:b-g80r09)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/pagePlayer/app.ts, line 122 at r1](https://reviewable.io/reviews/bloombooks/bloomplayer/22#-Li9KS3zCdqMmV3OCd-f:-LiAI1di-BfArtCjjpvp:b-ruqkw2) ([raw file](https://github.com/bloombooks/bloomplayer/blob/1461e42c4bb5552dadf0920476eec781c4210147/src/pagePlayer/app.ts#L122)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> totalVideoLength
> ```
getTotalVideoLength?
</blockquote></details>

Obsolete

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/22)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/pagePlayer/videoPlayer.ts, line 53 at r2](https://reviewable.io/reviews/bloombooks/bloomplayer/22#-LiAPUuW-AIkLAENnzpw:-LiAPUuW-AIkLAENnzpx:bjs0ikq) ([raw file](https://github.com/bloombooks/bloomplayer/blob/81b46df3036966ad0f65c0f9bd0c8f685ccfc644/src/pagePlayer/videoPlayer.ts#L53)):*
> ```
> reportVideoDuration
> ```
This would be more meaningful to me as reportVideoDurationPlayed or reportVideoPlayedDuration.
Up to you whether that's worth a change. Or just merge.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomplayer/22)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/pagePlayer/videoPlayer.ts, line 53 at r2](https://reviewable.io/reviews/bloombooks/bloomplayer/22#-LiAPUuW-AIkLAENnzpw:-LiDlcO86qk55nU3scKv:b-896fix) ([raw file](https://github.com/bloombooks/bloomplayer/blob/81b46df3036966ad0f65c0f9bd0c8f685ccfc644/src/pagePlayer/videoPlayer.ts#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> reportVideoDuration
> ```
This would be more meaningful to me as reportVideoDurationPlayed or reportVideoPlayedDuration.
Up to you whether that's worth a change. Or just merge.
</blockquote></details>

Done.

**Pull request merged**
